"""create core tables

Revision ID: 01aa7639864c
Revises: dcffe4d52241
Create Date: 2026-07-13 15:00:27.558554

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01aa7639864c"
down_revision: str | Sequence[str] | None = "dcffe4d52241"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parking_applications",
        sa.Column("preferred_floor", sa.SmallInteger(), nullable=False),
    )
    op.drop_column("parking_applications", "prefered_floor")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parking_applications",
        sa.Column("prefered_floor", sa.SMALLINT(), autoincrement=False, nullable=False),
    )
    op.drop_column("parking_applications", "preferred_floor")
    # ### end Alembic commands ###
