"""create core tables

Revision ID: 6e279ba8084d
Revises:
Create Date: 2026-07-09 21:58:02.214184

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mssql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e279ba8084d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("email", sa.Unicode(length=255), nullable=False),
        sa.Column("password_hash", sa.Unicode(length=255), nullable=True),
        sa.Column("first_name", sa.Unicode(length=100), nullable=False),
        sa.Column("last_name", sa.Unicode(length=100), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "USER",
                "SUPERVISOR",
                "ADMIN",
                name="user_role",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default=sa.text("'USER'"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "created_at",
            mssql.DATETIME2(precision=6),
            server_default=sa.text("SYSUTCDATETIME()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mssql.DATETIME2(precision=6),
            server_default=sa.text("SYSUTCDATETIME()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "parking_applications",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("registration_number", sa.Unicode(length=15), nullable=False),
        sa.Column("prefered_floor", sa.SmallInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "NEEDS_CHANGES",
                name="application_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column("supervisor_comment", sa.Unicode(length=1000), nullable=True),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", mssql.DATETIME2(precision=6), nullable=True),
        sa.Column(
            "created_at",
            mssql.DATETIME2(precision=6),
            server_default=sa.text("SYSUTCDATETIME()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mssql.DATETIME2(precision=6),
            server_default=sa.text("SYSUTCDATETIME()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_parking_applications_reviewed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_parking_applications_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parking_applications")),
    )
    op.create_index(
        "ix_parking_applications_registration_status",
        "parking_applications",
        ["registration_number", "status"],
        unique=False,
    )
    op.create_index(
        "ix_parking_applications_status_created_at",
        "parking_applications",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_parking_applications_user_id"),
        "parking_applications",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_parking_applications_user_id"), table_name="parking_applications"
    )
    op.drop_index(
        "ix_parking_applications_status_created_at", table_name="parking_applications"
    )
    op.drop_index(
        "ix_parking_applications_registration_status", table_name="parking_applications"
    )
    op.drop_table("parking_applications")
    op.drop_table("users")
    # ### end Alembic commands ###
