"""add refresh tokens

Revision ID: dcffe4d52241
Revises: 6e279ba8084d
Create Date: 2026-07-12 13:54:41.789420

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mssql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dcffe4d52241"
down_revision: str | Sequence[str] | None = "6e279ba8084d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("jti", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("token_hash", sa.Unicode(length=64), nullable=False),
        sa.Column("expires_at", mssql.DATETIME2(precision=6), nullable=False),
        sa.Column("revoked_at", mssql.DATETIME2(precision=6), nullable=True),
        sa.Column(
            "created_at",
            mssql.DATETIME2(precision=6),
            server_default=sa.text("SYSUTCDATETIME()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("jti", name=op.f("uq_refresh_tokens_jti")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
